"""add_urls_and_url_logs_tables

Revision ID: 604e8674793f
Revises: 7da3c7e09bfb
Create Date: 2025-11-25 10:41:33.068808

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "604e8674793f"
down_revision: Union[str, None] = "7da3c7e09bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chargebee_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("chargebee_customer_id", sa.String(length=255), nullable=False),
        sa.Column("plan_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_term_start", sa.TIMESTAMP(), nullable=True),
        sa.Column("current_term_end", sa.TIMESTAMP(), nullable=True),
        sa.Column("trial_end", sa.TIMESTAMP(), nullable=True),
        sa.Column("cancelled_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=255), nullable=True),
        sa.Column("subscription_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chargebee_subscription_id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index("idx_subscriptions_chargebee_id", "subscriptions", ["chargebee_subscription_id"], unique=False)
    op.create_index("idx_subscriptions_project_id", "subscriptions", ["project_id"], unique=False)
    op.create_index("idx_subscriptions_status", "subscriptions", ["status"], unique=False)
    op.create_table(
        "urls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("unique_identifier", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_urls_project_id", "urls", ["project_id"], unique=False)
    op.create_index("idx_urls_unique_identifier", "urls", ["unique_identifier"], unique=False)
    op.create_index(op.f("ix_urls_unique_identifier"), "urls", ["unique_identifier"], unique=True)
    op.create_table(
        "url_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("url_id", sa.String(length=36), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=True),
        sa.Column("query_params", sa.JSON(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_headers", sa.JSON(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["url_id"], ["urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_url_logs_created_at", "url_logs", ["created_at"], unique=False)
    op.create_index("idx_url_logs_url_id", "url_logs", ["url_id"], unique=False)
    op.add_column("job_executions", sa.Column("worker_id", sa.String(length=255), nullable=True))
    op.add_column("job_executions", sa.Column("duration_ms", sa.Integer(), nullable=True))
    op.add_column("job_executions", sa.Column("error", sa.Text(), nullable=True))
    op.add_column("job_executions", sa.Column("attempt", sa.Integer(), server_default="1", nullable=False))
    op.alter_column(
        "job_executions", "response_body", existing_type=mysql.MEDIUMTEXT(), type_=sa.Text(), existing_nullable=True
    )
    op.create_index("idx_job_executions_status", "job_executions", ["status"], unique=False)
    op.alter_column(
        "webhook_results", "request_body", existing_type=mysql.LONGTEXT(), type_=sa.Text(), existing_nullable=True
    )
    op.alter_column(
        "webhook_results", "response_body", existing_type=mysql.LONGTEXT(), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhook_results", "response_body", existing_type=sa.Text(), type_=mysql.LONGTEXT(), existing_nullable=True
    )
    op.alter_column(
        "webhook_results", "request_body", existing_type=sa.Text(), type_=mysql.LONGTEXT(), existing_nullable=True
    )
    op.drop_index("idx_job_executions_status", table_name="job_executions")
    op.alter_column(
        "job_executions", "response_body", existing_type=sa.Text(), type_=mysql.MEDIUMTEXT(), existing_nullable=True
    )
    op.drop_column("job_executions", "attempt")
    op.drop_column("job_executions", "error")
    op.drop_column("job_executions", "duration_ms")
    op.drop_column("job_executions", "worker_id")
    op.drop_index("idx_url_logs_url_id", table_name="url_logs")
    op.drop_index("idx_url_logs_created_at", table_name="url_logs")
    op.drop_table("url_logs")
    op.drop_index(op.f("ix_urls_unique_identifier"), table_name="urls")
    op.drop_index("idx_urls_unique_identifier", table_name="urls")
    op.drop_index("idx_urls_project_id", table_name="urls")
    op.drop_table("urls")
    op.drop_index("idx_subscriptions_status", table_name="subscriptions")
    op.drop_index("idx_subscriptions_project_id", table_name="subscriptions")
    op.drop_index("idx_subscriptions_chargebee_id", table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
