"""create tables

Revision ID: c46fb1088314
Revises:
Create Date: 2025-11-28 18:26:08.819994

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c46fb1088314"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_projects_user_id", "projects", ["user_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("schedule", sa.String(length=50), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=50), server_default="UTC", nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=True),
        sa.Column("last_run_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("next_run_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_jobs_enabled", "jobs", ["enabled"], unique=False)
    op.create_index("idx_jobs_next_run_at", "jobs", ["next_run_at"], unique=False)
    op.create_index("idx_jobs_project_id", "jobs", ["project_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "type",
            sa.Enum("email", "slack", "discord", "webhook", name="notification_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.String(length=10), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notifications_project_id", "notifications", ["project_id"], unique=False)
    op.create_index("idx_notifications_type", "notifications", ["type"], unique=False)
    op.create_index("idx_notifications_user_id", "notifications", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chargebee_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("chargebee_customer_id", sa.String(length=255), nullable=False),
        sa.Column("plan_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_term_start", sa.TIMESTAMP(), nullable=True),
        sa.Column("current_term_end", sa.TIMESTAMP(), nullable=True),
        sa.Column("trial_end", sa.TIMESTAMP(), nullable=True),
        sa.Column("cancelled_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=255), nullable=True),
        sa.Column("subscription_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chargebee_subscription_id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index("idx_subscriptions_chargebee_id", "subscriptions", ["chargebee_subscription_id"], unique=False)
    op.create_index("idx_subscriptions_project_id", "subscriptions", ["project_id"], unique=False)
    op.create_index("idx_subscriptions_status", "subscriptions", ["status"], unique=False)
    op.create_table(
        "urls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("unique_identifier", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_urls_project_id", "urls", ["project_id"], unique=False)
    op.create_index("idx_urls_unique_identifier", "urls", ["unique_identifier"], unique=False)
    op.create_index(op.f("ix_urls_unique_identifier"), "urls", ["unique_identifier"], unique=True)
    op.create_table(
        "job_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued", "running", "success", "failure", "timed_out", "dead_letter", name="execution_status_enum"
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("started_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_job_executions_created_at", "job_executions", ["created_at"], unique=False)
    op.create_index("idx_job_executions_job_id", "job_executions", ["job_id"], unique=False)
    op.create_index("idx_job_executions_status", "job_executions", ["status"], unique=False)
    op.create_table(
        "url_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("url_id", sa.String(length=36), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=True),
        sa.Column("query_params", sa.JSON(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_headers", sa.JSON(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["url_id"], ["urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_url_logs_created_at", "url_logs", ["created_at"], unique=False)
    op.create_index("idx_url_logs_url_id", "url_logs", ["url_id"], unique=False)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column(
            "method",
            sa.Enum("GET", "POST", "PUT", "PATCH", "DELETE", name="http_method_enum"),
            server_default="POST",
            nullable=False,
        ),
        sa.Column("headers", sa.JSON(), nullable=True),
        sa.Column("query_params", sa.JSON(), nullable=True),
        sa.Column("body_template", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=100), server_default="application/json", nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_webhooks_job_id", "webhooks", ["job_id"], unique=False)
    op.create_table(
        "webhook_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("webhook_id", sa.String(length=36), nullable=False),
        sa.Column("job_execution_id", sa.String(length=36), nullable=False),
        sa.Column("triggered_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("request_url", sa.String(length=1024), nullable=False),
        sa.Column("request_method", sa.String(length=10), nullable=False),
        sa.Column("request_headers", sa.JSON(), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_headers", sa.JSON(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("is_success", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["job_execution_id"], ["job_executions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_webhook_results_job_execution_id", "webhook_results", ["job_execution_id"], unique=False)
    op.create_index("idx_webhook_results_webhook_id", "webhook_results", ["webhook_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_webhook_results_webhook_id", table_name="webhook_results")
    op.drop_index("idx_webhook_results_job_execution_id", table_name="webhook_results")
    op.drop_table("webhook_results")
    op.drop_index("idx_webhooks_job_id", table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index("idx_url_logs_url_id", table_name="url_logs")
    op.drop_index("idx_url_logs_created_at", table_name="url_logs")
    op.drop_table("url_logs")
    op.drop_index("idx_job_executions_status", table_name="job_executions")
    op.drop_index("idx_job_executions_job_id", table_name="job_executions")
    op.drop_index("idx_job_executions_created_at", table_name="job_executions")
    op.drop_table("job_executions")
    op.drop_index(op.f("ix_urls_unique_identifier"), table_name="urls")
    op.drop_index("idx_urls_unique_identifier", table_name="urls")
    op.drop_index("idx_urls_project_id", table_name="urls")
    op.drop_table("urls")
    op.drop_index("idx_subscriptions_status", table_name="subscriptions")
    op.drop_index("idx_subscriptions_project_id", table_name="subscriptions")
    op.drop_index("idx_subscriptions_chargebee_id", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("idx_notifications_user_id", table_name="notifications")
    op.drop_index("idx_notifications_type", table_name="notifications")
    op.drop_index("idx_notifications_project_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("idx_jobs_project_id", table_name="jobs")
    op.drop_index("idx_jobs_next_run_at", table_name="jobs")
    op.drop_index("idx_jobs_enabled", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("idx_projects_user_id", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
